 <?php
// module/user/view/user/user/index.phtml:
$title = 'My users';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<table class="table">
	<tr>
		<th>Email</th>
		<th>Password</th>
		<th>Role</th>
		<th>&nbsp;</th>
	</tr>
 <?php foreach ($users as $user) : ?>
	<tr>
		<td><?php echo $this->escapeHtml($user->getEmail());?></td>
		<td><?php echo $this->escapeHtml($user->getPassword());?></td>
		<td><?php echo $this->escapeHtml($user->getRole());?></td>
		<td><a
			href="<?php
    
echo $this->url('user', array(
        'action' => 'edit',
        'id' => $user->getId()
    ));
    ?>" class="btn btn-primary">Edit</a> <a
			href="<?php
    
echo $this->url('user', array(
        'action' => 'delete',
        'id' => $user->getId()
    ));
    ?>" class="btn btn-danger">Delete</a>
		</td>

	</tr>
	<?php endforeach; ?>
 </table>